CREATE TABLE IF NOT EXISTS page_permissions (
  page_key     VARCHAR(100) NOT NULL,
  role         VARCHAR(50)  NOT NULL,
  access_level SMALLINT     NOT NULL DEFAULT 0,
  PRIMARY KEY (page_key, role)
);

INSERT INTO page_permissions (page_key, role, access_level) VALUES
  ('dashboard',       'super_admin',    2),
  ('dashboard',       'it_admin',       2),
  ('dashboard',       'supervisor',     1),
  ('dashboard',       'region_manager', 1),
  ('dashboard',       'sales_rep',      1),
  ('dashboard',       'fridge_admin',   0),
  ('dashboard',       'viewer',         1),

  ('invoices',        'super_admin',    2),
  ('invoices',        'it_admin',       2),
  ('invoices',        'supervisor',     1),
  ('invoices',        'region_manager', 1),
  ('invoices',        'sales_rep',      1),
  ('invoices',        'fridge_admin',   0),
  ('invoices',        'viewer',         1),

  ('reports',         'super_admin',    2),
  ('reports',         'it_admin',       2),
  ('reports',         'supervisor',     2),
  ('reports',         'region_manager', 2),
  ('reports',         'sales_rep',      2),
  ('reports',         'fridge_admin',   0),
  ('reports',         'viewer',         0),

  ('customer_detail', 'super_admin',    2),
  ('customer_detail', 'it_admin',       2),
  ('customer_detail', 'supervisor',     1),
  ('customer_detail', 'region_manager', 1),
  ('customer_detail', 'sales_rep',      1),
  ('customer_detail', 'fridge_admin',   0),
  ('customer_detail', 'viewer',         1),

  ('sales_activity',  'super_admin',    2),
  ('sales_activity',  'it_admin',       2),
  ('sales_activity',  'supervisor',     1),
  ('sales_activity',  'region_manager', 1),
  ('sales_activity',  'sales_rep',      1),
  ('sales_activity',  'fridge_admin',   0),
  ('sales_activity',  'viewer',         0),

  ('sales_tasks',     'super_admin',    2),
  ('sales_tasks',     'it_admin',       2),
  ('sales_tasks',     'supervisor',     2),
  ('sales_tasks',     'region_manager', 2),
  ('sales_tasks',     'sales_rep',      2),
  ('sales_tasks',     'fridge_admin',   1),
  ('sales_tasks',     'viewer',         0),

  ('fridges',         'super_admin',    2),
  ('fridges',         'it_admin',       2),
  ('fridges',         'supervisor',     0),
  ('fridges',         'region_manager', 1),
  ('fridges',         'sales_rep',      0),
  ('fridges',         'fridge_admin',   1),
  ('fridges',         'viewer',         0),

  ('stock',           'super_admin',    2),
  ('stock',           'it_admin',       2),
  ('stock',           'supervisor',     0),
  ('stock',           'region_manager', 0),
  ('stock',           'sales_rep',      0),
  ('stock',           'fridge_admin',   0),
  ('stock',           'viewer',         0),

  ('current_stock',   'super_admin',    2),
  ('current_stock',   'it_admin',       2),
  ('current_stock',   'supervisor',     0),
  ('current_stock',   'region_manager', 0),
  ('current_stock',   'sales_rep',      0),
  ('current_stock',   'fridge_admin',   0),
  ('current_stock',   'viewer',         0),

  ('upload',          'super_admin',    2),
  ('upload',          'it_admin',       2),
  ('upload',          'supervisor',     0),
  ('upload',          'region_manager', 0),
  ('upload',          'sales_rep',      0),
  ('upload',          'fridge_admin',   0),
  ('upload',          'viewer',         0),

  ('users',           'super_admin',    2),
  ('users',           'it_admin',       0),
  ('users',           'supervisor',     0),
  ('users',           'region_manager', 0),
  ('users',           'sales_rep',      0),
  ('users',           'fridge_admin',   0),
  ('users',           'viewer',         0),

  ('permissions',     'super_admin',    2),
  ('permissions',     'it_admin',       1),
  ('permissions',     'supervisor',     0),
  ('permissions',     'region_manager', 0),
  ('permissions',     'sales_rep',      0),
  ('permissions',     'fridge_admin',   0),
  ('permissions',     'viewer',         0)
ON CONFLICT DO NOTHING;
